
package com.integracao.tjsc.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "SeloService", targetNamespace = "http://www.tjsc.jus.br/selo", wsdlLocation = "http://selo.tjsc.jus.br/SeloService31Teste?wsdl")
public class SeloService_Service
    extends Service
{

    private final static URL SELOSERVICE_WSDL_LOCATION;
    private final static WebServiceException SELOSERVICE_EXCEPTION;
    private final static QName SELOSERVICE_QNAME = new QName("http://www.tjsc.jus.br/selo", "SeloService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://selo.tjsc.jus.br/SeloService31Teste?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SELOSERVICE_WSDL_LOCATION = url;
        SELOSERVICE_EXCEPTION = e;
    }

    public SeloService_Service() {
        super(__getWsdlLocation(), SELOSERVICE_QNAME);
    }

    public SeloService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), SELOSERVICE_QNAME, features);
    }

    public SeloService_Service(URL wsdlLocation) {
        super(wsdlLocation, SELOSERVICE_QNAME);
    }

    public SeloService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SELOSERVICE_QNAME, features);
    }

    public SeloService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SeloService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SeloService
     */
    @WebEndpoint(name = "SeloServicePort")
    public SeloService getSeloServicePort() {
        return super.getPort(new QName("http://www.tjsc.jus.br/selo", "SeloServicePort"), SeloService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SeloService
     */
    @WebEndpoint(name = "SeloServicePort")
    public SeloService getSeloServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.tjsc.jus.br/selo", "SeloServicePort"), SeloService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SELOSERVICE_EXCEPTION!= null) {
            throw SELOSERVICE_EXCEPTION;
        }
        return SELOSERVICE_WSDL_LOCATION;
    }

}
