
package com.integracao.tjsc.service;

import java.util.List;
import jakarta.activation.DataHandler;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "SeloService", targetNamespace = "http://www.tjsc.jus.br/selo")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SeloService {


    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.SituacaoTitulo>
     */
    @WebMethod
    @WebResult(name = "situacoesDeTitulo", targetNamespace = "")
    @RequestWrapper(localName = "getSituacoesDeTitulo", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetSituacoesDeTitulo")
    @ResponseWrapper(localName = "getSituacoesDeTituloResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetSituacoesDeTituloResponse")
    public List<SituacaoTitulo> getSituacoesDeTitulo();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.TipoCobranca>
     */
    @WebMethod
    @WebResult(name = "tiposDeCobranca", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeCobranca", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeCobranca")
    @ResponseWrapper(localName = "getTiposDeCobrancaResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeCobrancaResponse")
    public List<TipoCobranca> getTiposDeCobranca();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.TipoCobranca20>
     */
    @WebMethod
    @WebResult(name = "tiposDeCobranca20", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeCobranca20", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeCobranca20")
    @ResponseWrapper(localName = "getTiposDeCobranca20Response", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeCobranca20Response")
    public List<TipoCobranca20> getTiposDeCobranca20();

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.JuizPaz>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "juizesDePaz", targetNamespace = "")
    @RequestWrapper(localName = "getJuizesDePaz", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetJuizesDePaz")
    @ResponseWrapper(localName = "getJuizesDePazResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetJuizesDePazResponse")
    public List<JuizPaz> getJuizesDePaz(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param nupedido
     * @param user
     * @param isento
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "selosPedido", targetNamespace = "")
    @RequestWrapper(localName = "getSelosPedido", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetSelosPedido")
    @ResponseWrapper(localName = "getSelosPedidoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetSelosPedidoResponse")
    public byte[] getSelosPedido(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "nupedido", targetNamespace = "")
        Long nupedido,
        @WebParam(name = "isento", targetNamespace = "")
        Boolean isento)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.TipoSubestabelecimento>
     */
    @WebMethod
    @WebResult(name = "tiposDeSubestabelecimento", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeSubestabelecimento", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeSubestabelecimento")
    @ResponseWrapper(localName = "getTiposDeSubestabelecimentoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeSubestabelecimentoResponse")
    public List<TipoSubestabelecimento> getTiposDeSubestabelecimento();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.Banco>
     */
    @WebMethod
    @WebResult(name = "bancos", targetNamespace = "")
    @RequestWrapper(localName = "getBancos", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetBancos")
    @ResponseWrapper(localName = "getBancosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetBancosResponse")
    public List<Banco> getBancos();

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.CartorioLivro20>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "cartorioLivros20", targetNamespace = "")
    @RequestWrapper(localName = "getCartorioLivros20", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetCartorioLivros20")
    @ResponseWrapper(localName = "getCartorioLivros20Response", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetCartorioLivros20Response")
    public List<CartorioLivro20> getCartorioLivros20(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.Etnia>
     */
    @WebMethod
    @WebResult(name = "etnias", targetNamespace = "")
    @RequestWrapper(localName = "getEtnias", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetEtnias")
    @ResponseWrapper(localName = "getEtniasResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetEtniasResponse")
    public List<Etnia> getEtnias();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.TipoRegistroAverbacao>
     */
    @WebMethod
    @WebResult(name = "tiposDeRegistroDeAverbacao", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeRegistroDeAverbacao", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeRegistroDeAverbacao")
    @ResponseWrapper(localName = "getTiposDeRegistroDeAverbacaoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeRegistroDeAverbacaoResponse")
    public List<TipoRegistroAverbacao> getTiposDeRegistroDeAverbacao();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.TipoTelefone>
     */
    @WebMethod
    @WebResult(name = "tiposDeTelefone", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeTelefone", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeTelefone")
    @ResponseWrapper(localName = "getTiposDeTelefoneResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeTelefoneResponse")
    public List<TipoTelefone> getTiposDeTelefone();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.TipoTestamento>
     */
    @WebMethod
    @WebResult(name = "tiposDeTestamento", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeTestamento", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeTestamento")
    @ResponseWrapper(localName = "getTiposDeTestamentoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeTestamentoResponse")
    public List<TipoTestamento> getTiposDeTestamento();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.Comarca>
     */
    @WebMethod
    @WebResult(name = "comarcas", targetNamespace = "")
    @RequestWrapper(localName = "getComarcas", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetComarcas")
    @ResponseWrapper(localName = "getComarcasResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetComarcasResponse")
    public List<Comarca> getComarcas();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.TipoDocumento>
     */
    @WebMethod
    @WebResult(name = "tiposDeDocumento", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeDocumento", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeDocumento")
    @ResponseWrapper(localName = "getTiposDeDocumentoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeDocumentoResponse")
    public List<TipoDocumento> getTiposDeDocumento();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.TipoAto>
     */
    @WebMethod
    @WebResult(name = "tiposDeAto", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeAto", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeAto")
    @ResponseWrapper(localName = "getTiposDeAtoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeAtoResponse")
    public List<TipoAto> getTiposDeAto();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.TipoSelo>
     */
    @WebMethod
    @WebResult(name = "tiposDeSelo", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeSelo", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeSelo")
    @ResponseWrapper(localName = "getTiposDeSeloResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeSeloResponse")
    public List<TipoSelo> getTiposDeSelo();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.Moeda>
     */
    @WebMethod
    @WebResult(name = "moedas", targetNamespace = "")
    @RequestWrapper(localName = "getMoedas", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetMoedas")
    @ResponseWrapper(localName = "getMoedasResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetMoedasResponse")
    public List<Moeda> getMoedas();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.MotivoProtesto>
     */
    @WebMethod
    @WebResult(name = "motivosDeProtesto", targetNamespace = "")
    @RequestWrapper(localName = "getMotivosDeProtesto", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetMotivosDeProtesto")
    @ResponseWrapper(localName = "getMotivosDeProtestoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetMotivosDeProtestoResponse")
    public List<MotivoProtesto> getMotivosDeProtesto();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.EstadoCivil>
     */
    @WebMethod
    @WebResult(name = "estadosCivis", targetNamespace = "")
    @RequestWrapper(localName = "getEstadosCivis", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetEstadosCivis")
    @ResponseWrapper(localName = "getEstadosCivisResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetEstadosCivisResponse")
    public List<EstadoCivil> getEstadosCivis();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.Pais>
     */
    @WebMethod
    @WebResult(name = "paises", targetNamespace = "")
    @RequestWrapper(localName = "getPaises", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetPaises")
    @ResponseWrapper(localName = "getPaisesResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetPaisesResponse")
    public List<Pais> getPaises();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.Escolaridade>
     */
    @WebMethod
    @WebResult(name = "escolaridades", targetNamespace = "")
    @RequestWrapper(localName = "getEscolaridades", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetEscolaridades")
    @ResponseWrapper(localName = "getEscolaridadesResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetEscolaridadesResponse")
    public List<Escolaridade> getEscolaridades();

    /**
     * 
     * @param messageIDtransmissao
     * @param pass
     * @param user
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "reciboTSRarmazenado", targetNamespace = "")
    @RequestWrapper(localName = "verificaTransmissao", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.VerificaTransmissao")
    @ResponseWrapper(localName = "verificaTransmissaoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.VerificaTransmissaoResponse")
    public byte[] verificaTransmissao(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "messageIDtransmissao", targetNamespace = "")
        Integer messageIDtransmissao)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.EspecieTitulo>
     */
    @WebMethod
    @WebResult(name = "especiesDeTitulo", targetNamespace = "")
    @RequestWrapper(localName = "getEspeciesDeTitulo", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetEspeciesDeTitulo")
    @ResponseWrapper(localName = "getEspeciesDeTituloResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetEspeciesDeTituloResponse")
    public List<EspecieTitulo> getEspeciesDeTitulo();

    /**
     * 
     * @param pass
     * @param nupedido
     * @param user
     * @param isento
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "selosPedidoCompactados", targetNamespace = "")
    @RequestWrapper(localName = "getSelosPedidoCompactados", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetSelosPedidoCompactados")
    @ResponseWrapper(localName = "getSelosPedidoCompactadosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetSelosPedidoCompactadosResponse")
    public byte[] getSelosPedidoCompactados(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "nupedido", targetNamespace = "")
        Long nupedido,
        @WebParam(name = "isento", targetNamespace = "")
        Boolean isento)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.CartorioServentuario20>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "cartorioServentuarios20", targetNamespace = "")
    @RequestWrapper(localName = "getCartorioServentuarios20", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetCartorioServentuarios20")
    @ResponseWrapper(localName = "getCartorioServentuarios20Response", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetCartorioServentuarios20Response")
    public List<CartorioServentuario20> getCartorioServentuarios20(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.MotivoCancelProtesto>
     */
    @WebMethod
    @WebResult(name = "motivosDeCancelamentoDoProtesto", targetNamespace = "")
    @RequestWrapper(localName = "getMotivosDeCancelamentoDoProtesto", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetMotivosDeCancelamentoDoProtesto")
    @ResponseWrapper(localName = "getMotivosDeCancelamentoDoProtestoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetMotivosDeCancelamentoDoProtestoResponse")
    public List<MotivoCancelProtesto> getMotivosDeCancelamentoDoProtesto();

    /**
     * 
     * @param recibo
     * @param pass
     * @param user
     * @return
     *     returns com.integracao.tjsc.service.ReciboProtocolo
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "reciboDecodificado", targetNamespace = "")
    @RequestWrapper(localName = "decodificaRecibo", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.DecodificaRecibo")
    @ResponseWrapper(localName = "decodificaReciboResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.DecodificaReciboResponse")
    public ReciboProtocolo decodificaRecibo(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "recibo", targetNamespace = "")
        DataHandler recibo)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.JuizPaz20>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "juizesDePaz20", targetNamespace = "")
    @RequestWrapper(localName = "getJuizesDePaz20", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetJuizesDePaz20")
    @ResponseWrapper(localName = "getJuizesDePaz20Response", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetJuizesDePaz20Response")
    public List<JuizPaz20> getJuizesDePaz20(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.TipoServentuario>
     */
    @WebMethod
    @WebResult(name = "tiposDeServentuario", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeServentuario", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeServentuario")
    @ResponseWrapper(localName = "getTiposDeServentuarioResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeServentuarioResponse")
    public List<TipoServentuario> getTiposDeServentuario();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.ComarcaMunicipio>
     */
    @WebMethod
    @WebResult(name = "comarcasmunicipios", targetNamespace = "")
    @RequestWrapper(localName = "getComarcasMunicipios", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetComarcasMunicipios")
    @ResponseWrapper(localName = "getComarcasMunicipiosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetComarcasMunicipiosResponse")
    public List<ComarcaMunicipio> getComarcasMunicipios();

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.CartorioServentuario>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "cartorioServentuarios", targetNamespace = "")
    @RequestWrapper(localName = "getCartorioServentuarios", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetCartorioServentuarios")
    @ResponseWrapper(localName = "getCartorioServentuariosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetCartorioServentuariosResponse")
    public List<CartorioServentuario> getCartorioServentuarios(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.CartorioLivro>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "cartorioLivros", targetNamespace = "")
    @RequestWrapper(localName = "getCartorioLivros", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetCartorioLivros")
    @ResponseWrapper(localName = "getCartorioLivrosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetCartorioLivrosResponse")
    public List<CartorioLivro> getCartorioLivros(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.Profissao>
     */
    @WebMethod
    @WebResult(name = "profissoes", targetNamespace = "")
    @RequestWrapper(localName = "getProfissoes", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetProfissoes")
    @ResponseWrapper(localName = "getProfissoesResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetProfissoesResponse")
    public List<Profissao> getProfissoes();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.Cartorio>
     */
    @WebMethod
    @WebResult(name = "cartorios", targetNamespace = "")
    @RequestWrapper(localName = "getCartorios", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetCartorios")
    @ResponseWrapper(localName = "getCartoriosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetCartoriosResponse")
    public List<Cartorio> getCartorios();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.Municipio>
     */
    @WebMethod
    @WebResult(name = "municipios", targetNamespace = "")
    @RequestWrapper(localName = "getMunicipios", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetMunicipios")
    @ResponseWrapper(localName = "getMunicipiosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetMunicipiosResponse")
    public List<Municipio> getMunicipios();

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns int
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "numeroSelosLiberados", targetNamespace = "")
    @RequestWrapper(localName = "redisponibilizaUltimaTransmissaoSelos", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.RedisponibilizaUltimaTransmissaoSelos")
    @ResponseWrapper(localName = "redisponibilizaUltimaTransmissaoSelosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.RedisponibilizaUltimaTransmissaoSelosResponse")
    public int redisponibilizaUltimaTransmissaoSelos(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "selosCompactados", targetNamespace = "")
    @RequestWrapper(localName = "getSelosCompactados", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetSelosCompactados")
    @ResponseWrapper(localName = "getSelosCompactadosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetSelosCompactadosResponse")
    public byte[] getSelosCompactados(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.TipoEndereco>
     */
    @WebMethod
    @WebResult(name = "tiposDeEndereco", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeEndereco", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeEndereco")
    @ResponseWrapper(localName = "getTiposDeEnderecoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeEnderecoResponse")
    public List<TipoEndereco> getTiposDeEndereco();

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "selosAssinados", targetNamespace = "")
    @RequestWrapper(localName = "getSelos", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetSelos")
    @ResponseWrapper(localName = "getSelosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetSelosResponse")
    public byte[] getSelos(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.TipoAto20>
     */
    @WebMethod
    @WebResult(name = "tiposDeAto20", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeAto20", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeAto20")
    @ResponseWrapper(localName = "getTiposDeAto20Response", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeAto20Response")
    public List<TipoAto20> getTiposDeAto20();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.TipoProcuracao>
     */
    @WebMethod
    @WebResult(name = "tiposDeProcuracao", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeProcuracao", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeProcuracao")
    @ResponseWrapper(localName = "getTiposDeProcuracaoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeProcuracaoResponse")
    public List<TipoProcuracao> getTiposDeProcuracao();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.TipoEndosso>
     */
    @WebMethod
    @WebResult(name = "tiposDeEndosso", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeEndosso", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeEndosso")
    @ResponseWrapper(localName = "getTiposDeEndossoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeEndossoResponse")
    public List<TipoEndosso> getTiposDeEndosso();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.EnteDeclaradoUtilidadePublicaEstadual>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "entesDeclaradosUtilidadePublicaEstadual", targetNamespace = "")
    @RequestWrapper(localName = "getEntesDeclaradosUtilidadePublicaEstadual", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetEntesDeclaradosUtilidadePublicaEstadual")
    @ResponseWrapper(localName = "getEntesDeclaradosUtilidadePublicaEstadualResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetEntesDeclaradosUtilidadePublicaEstadualResponse")
    public List<EnteDeclaradoUtilidadePublicaEstadual> getEntesDeclaradosUtilidadePublicaEstadual()
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param arquivo
     * @param user
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "reciboTSR", targetNamespace = "")
    @RequestWrapper(localName = "putAtos", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.PutAtos")
    @ResponseWrapper(localName = "putAtosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.PutAtosResponse")
    public byte[] putAtos(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "arquivo", targetNamespace = "")
        DataHandler arquivo)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.Estado>
     */
    @WebMethod
    @WebResult(name = "estados", targetNamespace = "")
    @RequestWrapper(localName = "getEstados", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetEstados")
    @ResponseWrapper(localName = "getEstadosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetEstadosResponse")
    public List<Estado> getEstados();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.FormaPagamento>
     */
    @WebMethod
    @WebResult(name = "formasDePagamento", targetNamespace = "")
    @RequestWrapper(localName = "getFormasDePagamento", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetFormasDePagamento")
    @ResponseWrapper(localName = "getFormasDePagamentoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetFormasDePagamentoResponse")
    public List<FormaPagamento> getFormasDePagamento();

    /**
     * 
     * @return
     *     returns java.util.List<com.integracao.tjsc.service.TipoEmail>
     */
    @WebMethod
    @WebResult(name = "tiposDeEmail", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeEmail", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeEmail")
    @ResponseWrapper(localName = "getTiposDeEmailResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "com.integracao.tjsc.service.GetTiposDeEmailResponse")
    public List<TipoEmail> getTiposDeEmail();

}
